data "azurerm_client_config" "current" {}

data "azurerm_resource_group" "main" {
  name = var.resource_group_name
}

locals {
  token = lower(replace(var.environment_name, "-", ""))
  tags  = merge(var.tags, { "azd-env-name" = var.environment_name })
  apps = {
    for service in ["account", "payment", "transaction", "web"] :
    service => lookup(var.app_names, service, service == "web" ? "app-banking-web-${var.environment_name}" : "app-${service}-${var.environment_name}")
  }
  storage_name         = coalesce(var.storage_account_name, substr("st${local.token}", 0, 24))
  foundry_account_name = coalesce(var.foundry_account_name, "aif${substr(local.token, 0, 15)}${substr(sha1(var.subscription_id), 0, 6)}")
  foundry_project_name = coalesce(var.foundry_project_name, "foundry-${var.environment_name}")
}

resource "azurerm_log_analytics_workspace" "main" {
  name                = "log-${var.environment_name}"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.tags
}

resource "azurerm_application_insights" "main" {
  name                = "appi-${var.environment_name}"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  application_type    = "web"
  workspace_id        = azurerm_log_analytics_workspace.main.id
  tags                = local.tags
}

resource "azurerm_service_plan" "main" {
  name                = "asp-${var.environment_name}"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  os_type             = "Linux"
  sku_name            = var.plan_sku
  tags                = local.tags
}

# AzAPI creates the site so Azure's unique default hostname is set on the first PUT.
# An azurerm web app followed by an AzAPI patch would be too late for this setting.
resource "azapi_resource" "app" {
  for_each  = local.apps
  type      = "Microsoft.Web/sites@2024-11-01"
  name      = each.value
  location  = data.azurerm_resource_group.main.location
  parent_id = data.azurerm_resource_group.main.id
  tags      = merge(local.tags, { "azd-service-name" = each.key })
  identity {
    type = "SystemAssigned"
  }
  body = {
    kind = "app,linux"
    properties = merge({
      serverFarmId = azurerm_service_plan.main.id
      httpsOnly    = true
      siteConfig = {
        linuxFxVersion = each.key == "web" ? "NODE|22-lts" : "PYTHON|3.11"
        alwaysOn       = var.plan_sku != "F1" && var.plan_sku != "B1"
        appCommandLine = each.key == "web" ? "pm2 serve /home/site/wwwroot/dist --no-daemon --spa" : each.key == "payment" ? "python main.py" : "python -m uvicorn main:app --host 0.0.0.0 --port 8080"
        appSettings = concat([
          { name = "WEBSITES_PORT", value = "8080" },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = azurerm_application_insights.main.connection_string }
          ], each.key == "web" ? [
          { name = "SCM_DO_BUILD_DURING_DEPLOYMENT", value = "true" },
          { name = "POST_BUILD_COMMAND", value = "npm run build" }
        ] : [])
      }
      }, var.hostname_scope == null ? {} : {
      autoGeneratedDomainNameLabelScope = var.hostname_scope
    })
  }
  response_export_values = ["properties.defaultHostName", "identity.principalId"]
}

resource "azapi_update_resource" "payment_transaction_url" {
  type      = "Microsoft.Web/sites@2024-11-01"
  name      = azapi_resource.app["payment"].name
  parent_id = data.azurerm_resource_group.main.id
  body = {
    properties = {
      siteConfig = {
        appSettings = [
          { name = "TRANSACTIONS_API_SERVER_URL", value = "https://${azapi_resource.app["transaction"].output.properties.defaultHostName}" }
        ]
      }
    }
  }
  depends_on = [azapi_resource.app["payment"], azapi_resource.app["transaction"]]
}

resource "azurerm_storage_account" "content" {
  name                            = local.storage_name
  location                        = data.azurerm_resource_group.main.location
  resource_group_name             = data.azurerm_resource_group.main.name
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  account_kind                    = "StorageV2"
  min_tls_version                 = "TLS1_2"
  https_traffic_only_enabled      = true
  allow_nested_items_to_be_public = false
  tags                            = local.tags

  blob_properties {
    delete_retention_policy {
      days = 2
    }
  }
}

resource "azurerm_storage_container" "content" {
  name                  = var.storage_container_name
  storage_account_id    = azurerm_storage_account.content.id
  container_access_type = "private"
}

resource "azapi_resource" "foundry_account_dedicated" {
  type                      = "Microsoft.CognitiveServices/accounts@2025-06-01"
  name                      = local.foundry_account_name
  location                  = data.azurerm_resource_group.main.location
  parent_id                 = data.azurerm_resource_group.main.id
  schema_validation_enabled = false
  tags                      = local.tags
  identity {
    type = "SystemAssigned"
  }
  body = {
    kind = "AIServices"
    sku = {
      name = "S0"
    }
    properties = {
      customSubDomainName    = local.foundry_account_name
      disableLocalAuth       = false
      publicNetworkAccess    = "Enabled"
      allowProjectManagement = true
    }
  }
  response_export_values = ["properties.endpoint"]
}

resource "azapi_resource" "foundry_project" {
  type      = "Microsoft.CognitiveServices/accounts/projects@2025-06-01"
  name      = local.foundry_project_name
  parent_id = azapi_resource.foundry_account_dedicated.id
  location  = data.azurerm_resource_group.main.location
  tags      = local.tags
  identity {
    type = "SystemAssigned"
  }
  body = {
    properties = {}
  }
}
