data "azurerm_client_config" "current" {}

data "azurerm_resource_group" "main" {
  name = var.resource_group_name
}

locals {
  token = lower(replace(var.environment_name, "-", ""))
  tags  = merge(var.tags, { "azd-env-name" = var.environment_name })
  apps = {
    for service in ["account", "payment", "transaction", "web"] :
    service => lookup(var.app_names, service, service == "web" ? "app-banking-web-${var.environment_name}" : "app-${service}-${var.environment_name}")
  }
  storage_name             = coalesce(var.storage_account_name, substr("st${local.token}", 0, 24))
  foundry_account_name     = coalesce(var.foundry_account_name, "aif${substr(local.token, 0, 15)}${substr(sha1(var.subscription_id), 0, 6)}")
  foundry_project_name     = coalesce(var.foundry_project_name, "foundry-${var.environment_name}")
  foundry_project_endpoint = "https://${local.foundry_account_name}.services.ai.azure.com/api/projects/${local.foundry_project_name}"
  responses_bff_name       = lookup(var.app_names, "responses-bff", "app-responses-bff-${var.environment_name}")
  postgres_server_name     = coalesce(var.postgres_server_name, "pg-${var.environment_name}")
  postgres_database_url    = "postgresql+psycopg://${urlencode(var.postgres_admin_username)}:${urlencode(var.postgres_admin_password)}@${azapi_resource.postgres_server.output.properties.fullyQualifiedDomainName}:5432/${urlencode(var.postgres_database_name)}?sslmode=require"
}

resource "azurerm_log_analytics_workspace" "main" {
  name                = "log-${var.environment_name}"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.tags
}

resource "azurerm_application_insights" "main" {
  name                = "appi-${var.environment_name}"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  application_type    = "web"
  workspace_id        = azurerm_log_analytics_workspace.main.id
  tags                = local.tags
}

resource "azurerm_service_plan" "main" {
  name                = "asp-${var.environment_name}"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  os_type             = "Linux"
  sku_name            = var.plan_sku
  tags                = local.tags
}

# AzAPI creates the site so Azure's unique default hostname is set on the first PUT.
# An azurerm web app followed by an AzAPI patch would be too late for this setting.
resource "azapi_resource" "app" {
  for_each  = local.apps
  type      = "Microsoft.Web/sites@2024-11-01"
  name      = each.value
  location  = data.azurerm_resource_group.main.location
  parent_id = data.azurerm_resource_group.main.id
  tags      = merge(local.tags, { "azd-service-name" = each.key })
  identity {
    type = "SystemAssigned"
  }
  body = {
    kind = "app,linux"
    properties = merge({
      serverFarmId = azurerm_service_plan.main.id
      httpsOnly    = true
      siteConfig = {
        linuxFxVersion = each.key == "web" ? "NODE|22-lts" : "PYTHON|3.11"
        alwaysOn       = var.plan_sku != "F1" && var.plan_sku != "B1"
        appCommandLine = each.key == "web" ? "pm2 serve /home/site/wwwroot/dist --no-daemon --spa" : each.key == "payment" ? "python main.py" : "python -m uvicorn main:app --host 0.0.0.0 --port 8080"
        appSettings = concat([
          { name = "WEBSITES_PORT", value = "8080" },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = azurerm_application_insights.main.connection_string },
          { name = "SCM_DO_BUILD_DURING_DEPLOYMENT", value = "true" }
          ], each.key == "web" ? [
          { name = "POST_BUILD_COMMAND", value = "npm run build" }
          ] : concat([
            { name = "PORT", value = "8080" }
            ], contains(["account", "transaction"], each.key) ? [
            { name = "DATABASE_URL", value = local.postgres_database_url }
        ] : []))
      }
      }, var.hostname_scope == null ? {} : {
      autoGeneratedDomainNameLabelScope = var.hostname_scope
    })
  }
  response_export_values = ["properties.defaultHostName", "identity.principalId"]
}

resource "azapi_resource" "responses_bff" {
  type      = "Microsoft.Web/sites@2024-11-01"
  name      = local.responses_bff_name
  location  = data.azurerm_resource_group.main.location
  parent_id = data.azurerm_resource_group.main.id
  tags      = merge(local.tags, { "azd-service-name" = "responses-bff" })

  identity {
    type = "SystemAssigned"
  }

  body = {
    kind = "app,linux"
    properties = merge({
      serverFarmId = azurerm_service_plan.main.id
      httpsOnly    = true
      siteConfig = {
        linuxFxVersion = "PYTHON|3.11"
        alwaysOn       = var.plan_sku != "F1" && var.plan_sku != "B1"
        appCommandLine = "python -m uvicorn bff.main:app --host 0.0.0.0 --port 8080"
        appSettings = [
          { name = "WEBSITES_PORT", value = "8080" },
          { name = "PORT", value = "8080" },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = azurerm_application_insights.main.connection_string },
          { name = "SCM_DO_BUILD_DURING_DEPLOYMENT", value = "true" },
          { name = "PROFILE", value = "prod" },
          { name = "RESPONSES_UPSTREAM_MODE", value = "foundry" },
          { name = "RESPONSES_AGENT_ENDPOINT", value = "${local.foundry_project_endpoint}/agents/home-banking-agent/endpoint/protocols/openai/responses" },
          { name = "DATABASE_URL", value = local.postgres_database_url },
          { name = "ALLOWED_ORIGINS", value = jsonencode(["https://${azapi_resource.app["web"].output.properties.defaultHostName}"]) }
        ]
      }
      }, var.hostname_scope == null ? {} : {
      autoGeneratedDomainNameLabelScope = var.hostname_scope
    })
  }
  response_export_values = ["properties.defaultHostName", "identity.principalId"]
}

resource "azapi_update_resource" "payment_transaction_url" {
  type      = "Microsoft.Web/sites@2024-11-01"
  name      = azapi_resource.app["payment"].name
  parent_id = data.azurerm_resource_group.main.id
  body = {
    properties = {
      siteConfig = {
        appSettings = [
          { name = "WEBSITES_PORT", value = "8080" },
          { name = "PORT", value = "8080" },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = azurerm_application_insights.main.connection_string },
          { name = "SCM_DO_BUILD_DURING_DEPLOYMENT", value = "true" },
          { name = "TRANSACTIONS_API_SERVER_URL", value = "https://${azapi_resource.app["transaction"].output.properties.defaultHostName}" }
        ]
      }
    }
  }
  depends_on = [azapi_resource.app["payment"], azapi_resource.app["transaction"]]
}

resource "azapi_update_resource" "api_cors" {
  for_each  = toset(["account", "transaction"])
  type      = "Microsoft.Web/sites@2024-11-01"
  name      = azapi_resource.app[each.key].name
  parent_id = data.azurerm_resource_group.main.id
  body = {
    properties = {
      siteConfig = {
        cors = {
          allowedOrigins     = ["https://${azapi_resource.app["web"].output.properties.defaultHostName}"]
          supportCredentials = false
        }
        appSettings = [
          { name = "WEBSITES_PORT", value = "8080" },
          { name = "PORT", value = "8080" },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = azurerm_application_insights.main.connection_string },
          { name = "SCM_DO_BUILD_DURING_DEPLOYMENT", value = "true" },
          { name = "DATABASE_URL", value = local.postgres_database_url },
          { name = "CORS_ALLOWED_ORIGINS", value = "https://${azapi_resource.app["web"].output.properties.defaultHostName}" }
        ]
      }
    }
  }
}

resource "azapi_update_resource" "web_api_urls" {
  type      = "Microsoft.Web/sites@2024-11-01"
  name      = azapi_resource.app["web"].name
  parent_id = data.azurerm_resource_group.main.id
  body = {
    properties = {
      siteConfig = {
        appSettings = [
          { name = "WEBSITES_PORT", value = "8080" },
          { name = "APPLICATIONINSIGHTS_CONNECTION_STRING", value = azurerm_application_insights.main.connection_string },
          { name = "SCM_DO_BUILD_DURING_DEPLOYMENT", value = "true" },
          { name = "POST_BUILD_COMMAND", value = "npm run build" },
          { name = "VITE_ACCOUNT_API_URL", value = "https://${azapi_resource.app["account"].output.properties.defaultHostName}/api" },
          { name = "VITE_TRANSACTION_API_URL", value = "https://${azapi_resource.app["transaction"].output.properties.defaultHostName}/api" },
          { name = "VITE_RESPONSES_BFF_URL", value = "https://${azapi_resource.responses_bff.output.properties.defaultHostName}" },
          { name = "VITE_RESPONSES_API_URL", value = "https://${azapi_resource.responses_bff.output.properties.defaultHostName}/responses" }
        ]
      }
    }
  }
  depends_on = [azapi_resource.app["web"], azapi_resource.app["account"], azapi_resource.app["transaction"], azapi_resource.responses_bff]
}

resource "azurerm_storage_account" "content" {
  name                            = local.storage_name
  location                        = data.azurerm_resource_group.main.location
  resource_group_name             = data.azurerm_resource_group.main.name
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  account_kind                    = "StorageV2"
  min_tls_version                 = "TLS1_2"
  https_traffic_only_enabled      = true
  allow_nested_items_to_be_public = false
  tags                            = local.tags

  blob_properties {
    delete_retention_policy {
      days = 2
    }
  }
}

resource "azurerm_storage_container" "content" {
  name                  = var.storage_container_name
  storage_account_id    = azurerm_storage_account.content.id
  container_access_type = "private"
}

resource "azapi_resource" "postgres_server" {
  type      = "Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01"
  parent_id = data.azurerm_resource_group.main.id
  name      = local.postgres_server_name
  location  = coalesce(var.postgres_location, data.azurerm_resource_group.main.location)
  tags      = local.tags

  body = {
    properties = {
      administratorLogin         = var.postgres_admin_username
      administratorLoginPassword = var.postgres_admin_password
      authConfig = {
        activeDirectoryAuth = "Disabled"
        passwordAuth        = "Enabled"
      }
      backup = {
        backupRetentionDays = var.postgres_backup_retention_days
        geoRedundantBackup  = "Disabled"
      }
      createMode = "Default"
      highAvailability = {
        mode = "Disabled"
      }
      network = {
        publicNetworkAccess = "Enabled"
      }
      storage = {
        storageSizeGB = var.postgres_storage_mb / 1024
      }
      version = var.postgres_version
    }
    sku = {
      name = trimprefix(var.postgres_sku_name, "B_")
      tier = "Burstable"
    }
  }

  response_export_values = [
    "properties.administratorLogin",
    "properties.fullyQualifiedDomainName",
  ]
}

resource "azapi_resource" "postgres_database" {
  type      = "Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01"
  parent_id = azapi_resource.postgres_server.id
  name      = var.postgres_database_name

  body = {
    properties = {
      charset   = "UTF8"
      collation = "en_US.utf8"
    }
  }
}

resource "azapi_resource" "postgres_allow_azure_services" {
  type      = "Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01"
  parent_id = azapi_resource.postgres_server.id
  name      = "AllowAllAzureServicesAndResourcesWithinAzureIps"

  body = {
    properties = {
      startIpAddress = "0.0.0.0"
      endIpAddress   = "0.0.0.0"
    }
  }
}

# Opt-in: only created when postgres_allowed_client_ip is set, for example to let a
# developer reach the server directly from pgAdmin.
resource "azapi_resource" "postgres_allow_local_client" {
  count     = var.postgres_allowed_client_ip != null && var.postgres_allowed_client_ip != "" ? 1 : 0
  type      = "Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01"
  parent_id = azapi_resource.postgres_server.id
  name      = "AllowLocalClientIp"

  body = {
    properties = {
      startIpAddress = var.postgres_allowed_client_ip
      endIpAddress   = var.postgres_allowed_client_ip
    }
  }
}

resource "azapi_resource" "foundry_account_dedicated" {
  type                      = "Microsoft.CognitiveServices/accounts@2025-06-01"
  name                      = local.foundry_account_name
  location                  = data.azurerm_resource_group.main.location
  parent_id                 = data.azurerm_resource_group.main.id
  schema_validation_enabled = false
  tags                      = local.tags
  identity {
    type = "SystemAssigned"
  }
  body = {
    kind = "AIServices"
    sku = {
      name = "S0"
    }
    properties = {
      customSubDomainName    = local.foundry_account_name
      disableLocalAuth       = false
      publicNetworkAccess    = "Enabled"
      allowProjectManagement = true
    }
  }
  response_export_values = ["properties.endpoint"]
}

resource "azapi_resource" "foundry_project" {
  type      = "Microsoft.CognitiveServices/accounts/projects@2025-06-01"
  name      = local.foundry_project_name
  parent_id = azapi_resource.foundry_account_dedicated.id
  location  = data.azurerm_resource_group.main.location
  tags      = local.tags
  identity {
    type = "SystemAssigned"
  }
  body = {
    properties = {}
  }
}

resource "azurerm_role_assignment" "responses_bff_agent_consumer" {
  scope                            = azapi_resource.foundry_project.id
  role_definition_name             = "Foundry Agent Consumer"
  principal_id                     = azapi_resource.responses_bff.output.identity.principalId
  principal_type                   = "ServicePrincipal"
  skip_service_principal_aad_check = true
}

resource "azurerm_role_definition" "foundry_user_identity_impersonation" {
  name               = "Foundry Agent User Identity Impersonation"
  role_definition_id = uuidv5("url", "${data.azurerm_resource_group.main.id}/roles/foundry-agent-user-identity-impersonation")
  scope              = data.azurerm_resource_group.main.id
  description        = "Allows a trusted middle tier to delegate an authenticated end-user identity to Foundry hosted agents."

  permissions {
    data_actions = [
      "Microsoft.CognitiveServices/accounts/AIServices/agents/endpoints/UserIdentityImpersonation/action",
    ]
  }

  assignable_scopes = [data.azurerm_resource_group.main.id]
}

resource "azurerm_role_assignment" "responses_bff_user_identity_impersonation" {
  scope                            = azapi_resource.foundry_project.id
  role_definition_id               = azurerm_role_definition.foundry_user_identity_impersonation.role_definition_resource_id
  principal_id                     = azapi_resource.responses_bff.output.identity.principalId
  principal_type                   = "ServicePrincipal"
  skip_service_principal_aad_check = true
}
